FROM ubuntu:resolute

ENV ETOS_CONTEXT="ETR"
ENV ETR_PYTHON_VERSION=3.13

USER root

ENV VIRTUAL_ENV=/home/etos/.venv
ENV PATH="/home/etos/.venv/bin:${PATH}"
ENV TEST_FRAMEWORK_VENV=/home/etos/.test-framework
ENV TEST_ARTIFACT_PATH=/home/etos/artifacts
ENV GLOBAL_ARTIFACT_PATH=/home/etos/global
ENV TEST_LOCAL_PATH=/home/etos/local

# hadolint ignore=DL3008
RUN apt-get update -y && \
    apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses-dev \
    xz-utils tk-dev libffi-dev liblzma-dev git ca-certificates \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd -g 3705 etos && \
    useradd -u 3705 -g 3705 -ms /bin/bash etos

COPY --from=ghcr.io/astral-sh/uv:0.11.15 /uv /uvx /bin/

USER etos
WORKDIR /home/etos

# hadolint ignore=DL3013
RUN uv python install $ETR_PYTHON_VERSION && \
    uv venv --python $ETR_PYTHON_VERSION && \
    uv venv --python $ETR_PYTHON_VERSION $TEST_FRAMEWORK_VENV

COPY executor.sh /home/etos/executor.sh
ENTRYPOINT ["/home/etos/executor.sh"]
